In [ ]:
from sentence_transformers import SentenceTransformer
from transformers import default_data_collator
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np
import pandas as pd
from datasets import Dataset 
import torch
import re
import tensorflow as tf
import numpy as np
import re
from llm_to_change_real_to_fake import generate_fake_news

/media/tanmoy002/HDD/fake_real_news_pipeline/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-12-21 12:32:29.487871: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-21 12:32:29.532979: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-12-21 12:32:54.556406: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [2]:
# data=pd.read_excel("web_news.xlsx")

In [3]:
# # Check column names
# print("Columns in Excel:", data.columns.tolist())

# # Select 2nd and 4th columns (indexing starts at 0)
# selected_df = data.iloc[:, [2, 4]]  # 2nd column = index 1, 4th column = index 3

# # Optional: rename columns for clarity
# selected_df.columns = ['title', 'description']

# # Save to CSV
# selected_df.to_csv("web_news_selected.csv", index=False)

# print("Saved successfully as web_news_selected.csv")

In [2]:
data_ = pd.read_csv("web_news_selected_.csv", encoding="utf-8")
# Add a new column 'label' with all values 0
data_['label'] = 1

In [3]:
data_

,title,description,label
0,কুষ্টিয়ার এসপির নামে পুরনো ও ভুয়া নাচের ভিডি...,"“দেখুন কুষ্টিয়ার এসপি কি করছে, নাউজুবিল্লাহ, ন...",1
1,মিজানুর রহমান আজহারিকে চাঁদে দেখতে পাওয়ার গুজব,"সম্প্রতি, সামাজিক যোগাযোগ মাধ্যম ফেসবুকের একটি...",1
2,বদি ভাই খ্যাত অভিনেতা আব্দুল কাদেরের মৃত্যুর গুজব,ফেসবুকের বিভিন্ন আইডি ও পেজের মাধ্যমে গত ১৯ ডি...,1
3,সেনাবাহিনীর প্রথম নারী মেজর জেনারেলের ছবি বিকৃ...,"সম্প্রতি, সামাজিক যোগাযোগ মাধ্যম ফেসবুক ও ইউটি...",1
4,হ্যাকার হামজার পরিবর্তে ভিন্ন ছবি ব্যবহার করে ...,বিগত কয়েকবছর ধরে ফেসবুক এবং বিভিন্ন দেশী ভুঁই...,1
...,...,...,...
22062,অনুরূপ সেশনগুলিতে নূর ভাইকে একটি চিঠিও দেখা যাবে,"অভিনেতা আসাদুজ্জামান নূর, বাংলাদেশি কথাচিত্র প...",1
22063,Thai Parliament Ignites Diplomatic Crisis by D...,"In a surprise move, the Thai government has sp...",1
22064,Trump Lawyers Unveil Groundbreaking Proposal t...,"In a major development, President Trump's lega...",1
22065,Moscow Concert Hall Siege Ends with Unexpected...,"In a shocking turn of events, authorities reve...",1
22066,"""Gleneagles Hotel Named Top 'Waste-of-Money' D...",Gleneagles Hotel in Perth and Kinross has take...,1

In [4]:
# 1. Drop rows where the 'description' column is NaN
df_clean = data_.dropna(subset=['title', 'description'])
df_clean = df_clean[(df_clean['title'].str.strip() != '') & (df_clean['description'].str.strip() != '')]
# 2. Optional: reset index
df_clean = df_clean.reset_index(drop=True)

In [5]:
df_clean

,title,description,label
0,কুষ্টিয়ার এসপির নামে পুরনো ও ভুয়া নাচের ভিডি...,"“দেখুন কুষ্টিয়ার এসপি কি করছে, নাউজুবিল্লাহ, ন...",1
1,মিজানুর রহমান আজহারিকে চাঁদে দেখতে পাওয়ার গুজব,"সম্প্রতি, সামাজিক যোগাযোগ মাধ্যম ফেসবুকের একটি...",1
2,বদি ভাই খ্যাত অভিনেতা আব্দুল কাদেরের মৃত্যুর গুজব,ফেসবুকের বিভিন্ন আইডি ও পেজের মাধ্যমে গত ১৯ ডি...,1
3,সেনাবাহিনীর প্রথম নারী মেজর জেনারেলের ছবি বিকৃ...,"সম্প্রতি, সামাজিক যোগাযোগ মাধ্যম ফেসবুক ও ইউটি...",1
4,হ্যাকার হামজার পরিবর্তে ভিন্ন ছবি ব্যবহার করে ...,বিগত কয়েকবছর ধরে ফেসবুক এবং বিভিন্ন দেশী ভুঁই...,1
...,...,...,...
22062,অনুরূপ সেশনগুলিতে নূর ভাইকে একটি চিঠিও দেখা যাবে,"অভিনেতা আসাদুজ্জামান নূর, বাংলাদেশি কথাচিত্র প...",1
22063,Thai Parliament Ignites Diplomatic Crisis by D...,"In a surprise move, the Thai government has sp...",1
22064,Trump Lawyers Unveil Groundbreaking Proposal t...,"In a major development, President Trump's lega...",1
22065,Moscow Concert Hall Siege Ends with Unexpected...,"In a shocking turn of events, authorities reve...",1
22066,"""Gleneagles Hotel Named Top 'Waste-of-Money' D...",Gleneagles Hotel in Perth and Kinross has take...,1

In [6]:
data_real=pd.read_csv("real_news.csv")
data_real['label']=0

In [7]:
data_real

,id,ordering,datetime,agency,news_title,details_link,details_content,sentiment,summary,category_id,type,status,created_at,updated_at,district,thana,crime_name,processed,label
0,284,0,2024-01-30 03:12:40,Dawn,"TTP, IS-K, BLA behind 82pc deaths in terror at...",https://www.dawn.com/news/1803010/ttp-is-k-bla...,ISLAMABAD: Banned groups like the Tehreek-i-Ta...,"negative (polarity=-0.06416666666666665, subje...","Of these strikes, 97 occurred in KP, 28 in Bal...",3,web,1,2024-01-30 03:12:41,2024-01-30 03:12:41,NaN,NaN,"violence, killed",1,0
1,402,0,2024-01-30 09:52:37,Ananda Bazar,Terms of Use,https://www.anandabazar.com/termsofuse,These Terms of Use govern your use of the webs...,"positive (polarity=0.048377976190476166, subje...",These Terms of Use govern your use of the webs...,3,web,1,2024-01-30 09:52:38,2024-01-30 09:52:38,NaN,NaN,"Theft, Fraud, Perjury, violation",1,0
2,403,0,2024-01-30 09:52:37,Ananda Bazar,About Us,https://www.anandabazar.com/aboutus,আনন্দবাজার পত্রিকা যাত্রা শুরু করেছিল ১৩ মার্চ...,"positive (polarity=0.035695947570947566, subje...","আনন্দ বাজার ম্যাগাজিনটি March ই মার্চ, 1222 এ ...",3,web,1,2024-01-30 09:52:38,2024-01-30 09:52:38,NaN,NaN,NaN,1,0
3,404,0,2024-01-30 09:52:37,Ananda Bazar,Privacy Policy,https://www.anandabazar.com/privacy,"Last Updated on July 07, 2021 This Privacy Pol...","positive (polarity=0.04553719497749349, subjec...",The information gathered when you interact wit...,3,web,1,2024-01-30 09:52:38,2024-01-30 09:52:38,NaN,NaN,NaN,1,0
4,449,0,2024-01-30 09:56:05,The Washington Post,Tracking Biden administration political appoin...,https://www.washingtonpost.com/politics/intera...,The Washington Post is providing this importan...,"positive (polarity=0.09407547109752992, subjec...",The Washington Post and thePartnership for Pub...,2,web,1,2024-01-30 09:56:06,2024-01-30 09:56:06,NaN,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,201453,0,2024-03-28 19:07:36,Dainik Sylhet,ডেইলি সিলেট ডেস্ক :: বিয়ের প্রলোভনে প্রেমের সম...,https://dailysylhet.com/details/722589/,cialis fiyatcialis siparişhttp://umraniyetip...,"positive (polarity=0.06465909090909092, subjec...",সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,3,web,1,2024-03-28 19:07:36,2024-03-28 19:07:36,সুনামগঞ্জ,NaN,NaN,1,0
49996,201454,0,2024-03-28 19:07:36,Dainik Sylhet,ডেইলি সিলেট ডেস্ক :: পিংকু বিশ্বাস মৌলভীবাজারে...,https://dailysylhet.com/details/722586/,cialis fiyatcialis siparişhttp://umraniyetip...,"positive (polarity=0.047568118156353464, subje...",সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,3,web,1,2024-03-28 19:07:36,2024-03-28 19:07:36,মৌলভীবাজার,NaN,NaN,1,0
49997,201456,0,2024-03-28 19:07:36,Dainik Sylhet,ডেইলি সিলেট ডেস্ক :: যুক্তরাষ্ট্র প্রবাসী বাংল...,https://dailysylhet.com/details/722577/,cialis fiyatcialis siparişhttp://umraniyetip...,"positive (polarity=0.18938878581735724, subjec...",সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিপি: //umr...,3,web,1,2024-03-28 19:07:36,2024-03-28 19:07:36,সিলেট,NaN,হত্যা,1,0
49998,201457,0,2024-03-28 19:07:36,Dainik Sylhet,"দেশে কোটিপতি হিসাবধারীর সংখ্যা বেড়েছে ৬,৯৬২টি",https://dailysylhet.com/details/721989/,cialis fiyatcialis siparişhttp://umraniyetip...,"positive (polarity=0.06118561710398445, subjec...",সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,3,web,1,2024-03-28 19:07:36,2024-03-28 19:07:36,সিলেট,NaN,পাচার,1,0
49999,201458,0,2024-03-28 19:07:37,Dainik Sylhet,ভেজাল খাদ্যপণ্যে সয়লাব সিলেটের বাজার,https://dailysylhet.com/details/721982/,cialis fiyatcialis siparişhttp://umraniyetip...,"positive (polarity=0.05611849390919158, subjec...",সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিপি: //umr...,3,web,1,2024-03-28 19:07:37,2024-03-28 19:07:37,ঢাকা,NaN,বেপরোয়া,1,0

In [8]:
import pandas as pd

# Select 2nd, 4th, and 18th columns
selected_df_ = data_real.iloc[:, [4, 8, 18]]  

# Rename for clarity
selected_df_.columns = ['title', 'details_count', 'label']

# Drop rows where title and summary are exactly the same
# selected_df_ = selected_df_.drop_duplicates(subset=['title', 'details_count'], keep='first')
selected_df_.rename(columns={'details_count': 'description'}, inplace=True)
selected_df_ = selected_df_.dropna(subset=['title', 'description'])
selected_df_ = selected_df_[(selected_df_['title'].str.strip() != '') & (selected_df_['description'].str.strip() != '')]
# Optional: reset index
selected_df_ = selected_df_.reset_index(drop=True)

/tmp/ipykernel_17539/539936309.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_df_.rename(columns={'details_count': 'description'}, inplace=True)

In [9]:
selected_df_

,title,description,label
0,"TTP, IS-K, BLA behind 82pc deaths in terror at...","Of these strikes, 97 occurred in KP, 28 in Bal...",0
1,Terms of Use,These Terms of Use govern your use of the webs...,0
2,About Us,"আনন্দ বাজার ম্যাগাজিনটি March ই মার্চ, 1222 এ ...",0
3,Privacy Policy,The information gathered when you interact wit...,0
4,Tracking Biden administration political appoin...,The Washington Post and thePartnership for Pub...,0
...,...,...,...
49995,ডেইলি সিলেট ডেস্ক :: বিয়ের প্রলোভনে প্রেমের সম...,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,0
49996,ডেইলি সিলেট ডেস্ক :: পিংকু বিশ্বাস মৌলভীবাজারে...,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,0
49997,ডেইলি সিলেট ডেস্ক :: যুক্তরাষ্ট্র প্রবাসী বাংল...,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিপি: //umr...,0
49998,"দেশে কোটিপতি হিসাবধারীর সংখ্যা বেড়েছে ৬,৯৬২টি",সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,0
49999,ভেজাল খাদ্যপণ্যে সয়লাব সিলেটের বাজার,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিপি: //umr...,0

In [10]:
print(selected_df_.columns)

Index(['title', 'description', 'label'], dtype='object')

In [13]:
# selected_df_random = selected_df_.sample(45000, random_state=42)
# import time
# # Generate fake news with retries
# for idx, row in selected_df_random.iterrows():
#     fake_title, fake_description = generate_fake_news(row["title"], row["description"])
#     if fake_title == "N/A" or fake_description == "N/A":
#         print(f"Skipping row {idx} due to generation failure.")
#         continue
#     else:
#         print("\nOriginal Real News:")
#         print(row["title"], "\n", row["description"])
#         print("\nGenerated Fake News:")
#         print(fake_title, "\n", fake_description)
#         print("\n")
    
#     time.sleep(0.5)

In [11]:
# Merge the two dataframes
merged_df = pd.concat([df_clean, selected_df_], ignore_index=True)
# Convert 'title' and 'description' columns to lowercase
merged_df['title'] = merged_df['title'].str.lower()
merged_df['description'] = merged_df['description'].str.lower()

In [12]:
merged_df

,title,description,label
0,কুষ্টিয়ার এসপির নামে পুরনো ও ভুয়া নাচের ভিডি...,"“দেখুন কুষ্টিয়ার এসপি কি করছে, নাউজুবিল্লাহ, ন...",1
1,মিজানুর রহমান আজহারিকে চাঁদে দেখতে পাওয়ার গুজব,"সম্প্রতি, সামাজিক যোগাযোগ মাধ্যম ফেসবুকের একটি...",1
2,বদি ভাই খ্যাত অভিনেতা আব্দুল কাদেরের মৃত্যুর গুজব,ফেসবুকের বিভিন্ন আইডি ও পেজের মাধ্যমে গত ১৯ ডি...,1
3,সেনাবাহিনীর প্রথম নারী মেজর জেনারেলের ছবি বিকৃ...,"সম্প্রতি, সামাজিক যোগাযোগ মাধ্যম ফেসবুক ও ইউটি...",1
4,হ্যাকার হামজার পরিবর্তে ভিন্ন ছবি ব্যবহার করে ...,বিগত কয়েকবছর ধরে ফেসবুক এবং বিভিন্ন দেশী ভুঁই...,1
...,...,...,...
72062,ডেইলি সিলেট ডেস্ক :: বিয়ের প্রলোভনে প্রেমের সম...,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,0
72063,ডেইলি সিলেট ডেস্ক :: পিংকু বিশ্বাস মৌলভীবাজারে...,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,0
72064,ডেইলি সিলেট ডেস্ক :: যুক্তরাষ্ট্র প্রবাসী বাংল...,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিপি: //umr...,0
72065,"দেশে কোটিপতি হিসাবধারীর সংখ্যা বেড়েছে ৬,৯৬২টি",সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিটিপি: //u...,0
72066,ভেজাল খাদ্যপণ্যে সয়লাব সিলেটের বাজার,সিআইলিস ফাইয়েটসিয়ালিস সিপারিআইএইচটিপি: //umr...,0

In [13]:
# Remove duplicates based on title and description
# merged_df_ = merged_df.drop_duplicates(subset=['title', 'description'], keep='first')
# Shuffle randomly
merged_df_ = merged_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [14]:
merged_df_

,title,description,label
0,আজ বৃহত্তর জামাতে ইসলামের বিএনপি শাখার একটি প্...,বিজ্ঞপ্তীটি অবিক্রিত অবস্থায় প্রকাশ করা হল একট...,1
1,বাংলাদেশের প্রথম জুগন্তর পত্রিকার বারিসাল ব্যু...,জুগন্তর পত্রিকার বারিশাল ব্যুরো থেকে প্রতিদিনে...,1
2,আরটিজেএ নির্বাচনে লড়ছেন ১৫ প্রার্থী,"আখতার রহমান, ইএমএসএস, গণ যোগাযোগ ও সাংবাদিকতা,...",0
3,"ukraine secretly builds ""doomsday"" arsenal to ...","in a shocking revelation, high-ranking officia...",1
4,"পড়াশোনা আসলে চাকরি পাওয়ার জন্য নয়, জ্ঞান অর্জন...",উত্স: আজকের ম্যাগাজিন অনলাইন নিউজ: মোহানগঞ্জ উ...,0
...,...,...,...
72062,the icon interview: will of steel,"“in modelling, you’re expected to look glamoro...",0
72063,"চিট্টাগংয়ের হাথাজারীতে 10 জন নিহত, 20 জন আহত",সোমবার (29th november) দুপুর 12:00 pm-এ চিট্টা...,1
72064,বিস্তারিত,"হারুন, কাউন্সিলর জাফরুল হায়দার এবং অন্যান্য ও...",0
72065,আর্থিক প্রতারণার উদ্দেশ্যে ভারতীয় শিশু আরাসালা...,সম্প্রতি “আমিন না লিখে যাবেন না ” শীর্ষক শিরোন...,1
72066,"রাজশাহীর গোদাগাড়ীতে সিপিএসসি, র‌্যাব-৫ অন্তর্ভ...",শিলট জেলা পুলিস ও ডিআইবি-৫ তারা একটি অভিযানের ...,1

In [19]:
merged_df_.to_csv("final_dataset.csv", encoding="utf-8",index=False)

In [20]:
temp_data=pd.read_csv("final_dataset.csv")
temp_data.head

<bound method NDFrame.head of                                                    title  \
0      আজ বৃহত্তর জামাতে ইসলামের বিএনপি শাখার একটি প্...
1      বাংলাদেশের প্রথম জুগন্তর পত্রিকার বারিসাল ব্যু...
2                    আরটিজেএ নির্বাচনে লড়ছেন ১৫ প্রার্থী
3      ukraine secretly builds "doomsday" arsenal to ...
4      পড়াশোনা আসলে চাকরি পাওয়ার জন্য নয়, জ্ঞান অর্জন...
...                                                  ...
72062                  the icon interview: will of steel
72063      চিট্টাগংয়ের হাথাজারীতে 10 জন নিহত, 20 জন আহত
72064                                          বিস্তারিত
72065  আর্থিক প্রতারণার উদ্দেশ্যে ভারতীয় শিশু আরাসালা...
72066  রাজশাহীর গোদাগাড়ীতে সিপিএসসি, র‌্যাব-৫ অন্তর্ভ...

                                             description  label
0      বিজ্ঞপ্তীটি অবিক্রিত অবস্থায় প্রকাশ করা হল একট...      1
1      জুগন্তর পত্রিকার বারিশাল ব্যুরো থেকে প্রতিদিনে...      1
2      আখতার রহমান, ইএমএসএস, গণ যোগাযোগ ও সাংবাদিকতা,...      0
3      in a shocking revelation, high-ranking officia...      1
4      উত্স: আজকের ম্যাগাজিন অনলাইন নিউজ: মোহানগঞ্জ উ...      0
...                                                  ...    ...
72062  “in modelling, you’re expected to look glamoro...      0
72063  সোমবার (29th november) দুপুর 12:00 pm-এ চিট্টা...      1
72064  হারুন, কাউন্সিলর জাফরুল হায়দার এবং অন্যান্য ও...      0
72065  সম্প্রতি “আমিন না লিখে যাবেন না ” শীর্ষক শিরোন...      1
72066  শিলট জেলা পুলিস ও ডিআইবি-৫ তারা একটি অভিযানের ...      1

[72067 rows x 3 columns]>

In [ ]:
temp_data.columns

Index(['title', 'description', 'label'], dtype='object')

:

In [18]:
# 1. Load the model
model_embedding = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [19]:
# 3. Combine title and summary for embeddings
texts = (merged_df_['title'] + ". " + merged_df_['description']).tolist()
labels = merged_df_['label'].tolist()  # 0 = Real, 1 = Fake

In [20]:
texts

['আজ বৃহত্তর জামাতে ইসলামের বিএনপি শাখার একটি প্রেস বিজ্ঞপ্তী মতিকণ্ঠে এসে পৌছেছে. বিজ্ঞপ্তীটি অবিক্রিত অবস্থায় প্রকাশ করা হল একটা ঘষোনাবৃহত্তর জামাতে ইসলামের বিএনপি শাখার ভবিষ্যত কান্ডারি তারেক জিয়া লন্ডনে দির্ঘ কাল বেপি চিকিৎস্বাধীন জীবন যাপন করছেন  কোমর ও মেরু দন্ড সারানোর পর এখন দু দন্ড সময় বেয় করে তিনি বাকশালী ভন্ড স্ট্রেটেজি পন্ড করে খন্ড খন্ড গন্ডগোল বাধিয়ে দিতে সক্ষম হয়েছেন  দেশ জুড়ে এখন চলছে মনির পোড়ানর উৎসব  এ উপলখ্যে তিনি একটি ভিডিও বার্তা প্রকাশ করেছেন ভিডিও তে তিনি বলেছেন, শান্তির জন্য শক্তি প্রয়গ করা প্রয়জন  এটা পৃথিবির ইতিহাসে হয়েছে, আমাদের ইসলাম ধর্মেও হয়েছে বিএনপি শাখার চলমান অবরধ আন্দলনকে শান্তিকামি আক্ষা দিয়ে এর সহিত ইসলামের আন্দলনের মিল খুজে পাওয়ার কৃতিত্তের স্বিকৃতি হিসাবে বিএনপি শাখার পক্ষ হতে একটি সন্মান সুচক উপাধি তার নামের শেষে ব্রেকেটে যোগ করার সিদ্ধান্ত নেওয়া হয়েছে এখন হতে তার পুর্ন নাম – তারেক জিয়া (খাঃ পুঃ), এখানে খাঃ পুঃ অর্থ খালেদার পুত্র  বস্তুত ছোট গনতন্ত্রের মৃত্যুর পর উপাধির দাবিটি তার একচ্ছত্র হয়েছে বিএনপি শাখার আরেকটি সিদ্ধান্ত অনুযায়ি গনতন্ত্রের ছোট অংশটিও তারেক জিয়া (খাঃ পুঃ) এর শক্ত কাধে নেস্ত করা হল  তিনি এখন আস্ত গনতন্ত্র  যদিও কিছু দিন পুর্বেও পুর্ন গনতন্ত্রের ভার নিজের কাধে নিবার অবস্থা তার ছিল না লন্ডন যাত্রার প্রাক্কালে তার শরির সাস্থের এক্স রেতবে লন্ডনে দির্ঘ কাল চিকিৎস্বাধীন জীবন যাপন করার পর তার মেরু দন্ড ও কোমর শক্ত হয়েছে  এখন গনতন্ত্র মানেই তারেক জিয়া (খাঃ পুঃ) বৃহত্তর জামাতে ইসলামের বিএনপি শাখার সদর দপ্তরঢাকাবাংলাদেশ',
 'বাংলাদেশের প্রথম জুগন্তর পত্রিকার বারিসাল ব্যুরো রিপোর্টার এখন নিঃসঙ্গ. জুগন্তর পত্রিকার বারিশাল ব্যুরো থেকে প্রতিদিনের সংবাদ সহজেই মানুষ খুঁজছেন, কিন্তু এখন ভালো-মন্দ বিশ্বাস করা যাচ্ছে না। কারণ হলো জুগন্তর পত্রিকার বারিশাল ব্যুরো থেকে এক সাংবাদিক নিঃসঙ্গ হওয়ার অভিজ্ঞতা।  জুগন্তর পত্রিকার এই সাংবাদিকের নাম আছে সাংবাদিক এসএন পালাশ। জুগন্তর পত্রিকা অধীনে যোগদানের ৫ মাস আগে, চারটি বিভাগে জুগন্তর পত্রিকা অধীনে যোগদান।  এই সাংবাদিক মাহি শহর, ভোলা, ঝালকাঠি ও পটুয়াখালি থেকে এই সাংবাদিক অন্তর্ধান।  জুগন্তর পত্রিকা অফিসের মো: আরশাদ-উল-হাবীব, এভি, ওয়ারেন্ট ইঞ্জিনিয়ার জার্নালিস্ট মো: কাদের-উজ-জামান (বুশান)  এখন পর্যন্ত জুগন্তর পত্রিকা অধীনে চারটি বিভাগে ৫ মাস আগে একাই নিয়োগ হওয়ার পর থেকে জুগন্তর পত্রিকা অধীনে চারটি বিভাগের এই ৫ মাস আগে থেকে নিয়োগ, জুগন্তর পত্রিকা অধীনে।',
 'আরটিজেএ নির্বাচনে লড়ছেন ১৫ প্রার্থী. আখতার রহমান, ইএমএসএস, গণ যোগাযোগ ও সাংবাদিকতা, রব: ইসলাম্মারসা মোরা, বোয়ালিয়া, রাজশাহী। রিপোর্টার শাহেন আলম। তারা হলেন বিভাগ কমিশন নির্বাচন কমিশন কর্তৃক এই বছরের নির্বাচনকে সংযুক্ত করছে। অন্য দুই সদস্য হলেন অধ্যাপক ড। প্রদীপ কুমার পান্ডে এবং অ্যাডভোকেট মোমিনুল ইসলাম বাবু। 12 ফেব্রুয়ারি সন্ধ্যা 5 টা থেকে বিকেল ৫ টা থেকে বিকাল ৫ টা পর্যন্ত মনোনয়নের কাগজপত্রগুলি তদন্তের পরে। february ফেব্রুয়ারি nomeনিজস্ব প্রতিনিধি: ২ february ফেব্রুয়ারি, সাত জন প্রার্থী রাজশাহী টেলিভিশন সাংবাদিক সমিতি-এটিজেএর দ্বি-বার্ষিক নির্বাচনের সাতটি পদে প্রতিদ্বন্দ্বিতা করছেন। বুধবার মনোনয়নের কাগজপত্র সংগ্রহের দিন পর্যন্ত জীবনযাত্রার সময়কালের জন্য মনোনয়নের কাগজপত্র। জোনালের প্রতিনিধি বদরুল হাসান লিটন, ডিবিসি, ডিবিসি, ডিবিসি নিউজ চিফ সৌরাব এবং মোহানা টিভি ব্যুরো প্রধান মেহদী হাসান শ্যাম। তারা টিভিএস এসওএফ রিপোর্টার এমডি।মোস্তফিজুর রহমান।আমির ফয়সাল এবং টিভি ভিডিও গ্রাফার হাবিবুর রহমান পাপু। তারা হলেন আমার টিভি শাহরিয়ার রাজশাহী বিভাগীয় প্রতিনিধি, গোলাম রাব্বানি এবং স্বতন্ত্র টিভি রিপোর্টার এমডি।',
 'ukraine secretly builds "doomsday" arsenal to counter russian threats. in a shocking revelation, high-ranking officials within ukroboronprom have confirmed that the state-owned defense company has been secretly building an elite "doomsday" arsenal in response to russia\'s escalating aggression. according to sources close to the project, this top-secret facility is capable of producing advanced missiles and drones at an unprecedented rate, with some experts speculating that it could potentially outproduce even the united states. the project, codenamed "dragon\'s breath," aims to create a powerful counterweight to russia\'s military might and has been allegedly supported by clandestine western allies. despite initial skepticism from critics who pointed out the immense logistical challenges of such an undertaking, insiders claim that ukraine has already made significant breakthroughs in mastering cutting-edge production techniques. as one official noted, "we\'re not just building tanks and guns – we\'re creating a game-changer." however, when questioned about the exact timeline for completion and deployment, officials remained tight-lipped, fueling speculation about the true extent of this covert operation.',
 'পড়াশোনা আসলে চাকরি পাওয়ার জন্য নয়, জ্ঞান অর্জনের জন্যঃ ইউএনও. উত্স: আজকের ম্যাগাজিন অনলাইন নিউজ: মোহানগঞ্জ উপজিলা নির্বাহী কর্মকর্তা (ইউএনও) ছাব্বির আহমেদ আকুনজি বলেছেন যে গবেষণাটি আসলে চাকরি পাচ্ছে না, তবে জ্ঞান লাভের জন্য। একজন প্রাক্তন dhaka াকা কলেজের শিক্ষার্থী তার নিজস্ব একাডেমিক পুড়ে যাওয়ার প্রতিক্রিয়ায় এটি বলেছিলেনসরকারী চাকরি না পাওয়ার জন্য মঙ্গলবার রাতে শংসাপত্রগুলি। ইউনো বলেছিলেন যে অর্জিত জ্ঞান সর্বস্তরের ক্ষেত্রে কার্যকর হবে everহতাশাগুলি আর থাকবে না।মোহানগঞ্জ পৌরসভার দেওথান গ্রামের শামসুর রহমানের পুত্র। শহরের স্টেশন রোডে \'কুতুম ঘর\' নামে একটি রেস্তোঁরা রয়েছে।মোহাঙ্গান পাইলট সরকারী উচ্চ বিদ্যালয় থেকে এসএসসি এবং আলমগির মনসুর (মিন্টু) মেমেনসিংহে আলমগির মনসুর (মিন্টু) মেমোরিয়াল কলেজ থেকে এইচএসসি 21. ল্যাটারের, তিনি dhaka াকা কলেজ থেকে দর্শনে সম্মান ও স্নাতকোত্তর সম্পন্ন করেছেন। এই গবেষণার পরে, সরকার এমনকি চাকরি পেলেন না, পরেও সরকার চাকরি পাননিবিভিন্ন সরকারী অফিসে কর্মসংস্থানের জন্য একাধিক আপিল। চাকরির বয়সের পরে তিনি তার শহরে রেস্তোঁরা ব্যবসা শুরু করেছিলেন। ক্রোধের বিষয়টি প্রকাশ করে সালাম বলেছিলেন, “আমি নামী শিক্ষাপ্রতিষ্ঠানগুলিতে পড়াশোনা করেছি। ফলাফলটিও ভাল। তবে সেখানে ছিলঅসংখ্য অ্যাপ্লিকেশন, তবে কোনও চাকরি ছিল না ut তবে কম প্রতিভাবান লোকেরাও তদবিরের মাধ্যমে চাকরি পেয়েছিলেন।ওনলিন নিউজ: নেট্রোকোনা ছাব্বির আহমেদ আকুনজি বলেছিলেন যে মোহনগঞ্জ উপজিলা নির্বাহী কর্মকর্তা (ইউএনও) বলেছেন যে গবেষণাটি আসলে কাজের জন্য নয়, তবে একজন dhaka াকা কলেজের প্রাক্তন শিক্ষার্থী মঙ্গলবার তার নিজস্ব সমস্ত শিক্ষাগত শংসাপত্র পোড়ানোর প্রতিক্রিয়ায় এটি বলেছিলেনসরকারী চাকরি না পাওয়ার জন্য ক্রোধে রাতমঙ্গলবার রাতে আরিলিয়ার থাকবেন, সালাম নেট্রোকোনার মোহানগঞ্জ পৌরসভার একটি রেস্তোঁরার ভিতরে তার শংসাপত্রগুলি পুড়িয়ে ফেলেন।মোহনগঞ্জ পৌরসভার দেওথান গ্রামের রহমান। শহরের স্টেশন রোডে \'কুতুম ঘর\' নামে একটি রেস্তোঁরা রয়েছে।পাইলট সরকার উচ্চ বিদ্যালয় এবং আলমগির মনসুর (মিন্টু) মেমেনসিংহের 21 শে -র মধ্যে এইচএসসি থেকে এইচএসসি dhakaবিভিন্ন সরকারী অফিসে কর্মসংস্থান। চাকরির বয়সের পরে, তিনি তার শহরে রেস্তোঁরা ব্যবসা শুরু করেছিলেন। ক্রোধকে প্রকাশ করে সালাম বলেছিলেন, “আমি নামী শিক্ষাপ্রতিষ্ঠানে পড়াশোনা করেছি। ফলাফলটিও ভাল। তবে সেখানে অসংখ্য অ্যাপ্লিকেশন ছিল,তবে কোনও চাকরি ছিল না ut তবে কম প্রতিভাবান লোকেরাও তদবিরের মাধ্যমে চাকরি পেয়েছিলেন।"সালাম বলেছিলেন," সিদ্ধান্ত নেওয়া হয়নি যে মন্ত্রী প্রত্যেকের জন্য শংসাপত্র জ্বালানোর জন্য বয়সের সীমা ঠিক করেননি। "তিনি আরও যোগ করেছেন," এখন আমার বয়স 5 বছর। কোনও সরকারী-বেসরকারী চাকরীর জন্য আবেদন করার সময় নেই।ওকাজো এই শংসাপত্রটি পুড়িয়ে দিয়েছে তাই আমি পোড়া করেছি। আমি সরকারী চাকরিতে প্রবেশের বয়সের সীমা বাড়িয়ে তুলছি। আওয়ামী পরিবারের শুরু থেকে, আমি বিসিএল রাজনীতির সাথে যুক্ত ছিলাম।একের জন্য পৃথক নিয়ম হয়ে উঠুন। প্রত্যেকের জন্য চাকরির বয়সের সীমা বাড়ানো দরকার never ততক্ষণ প্রত্যেকে এই সুযোগটি পাবে।',
 "». :: বিএনপির স্থায়ী কমিটির সদস্য গায়েশ্বর চন্দ্র রায় বলেছেন যে এই সরকারের শাসন জনগণকে ভেঙে দেবে, বিএনপি পক্ষে থাকবে। সুতরাং এখন ক্ষমতাসীন আওয়ামী লীগ সংরক্ষিত মহিলাদের জন্য পার্টির মনোনয়ন ফর্ম বিক্রি শুরু করেছেদ্বাদশ সংসদে আসন। আওয়ামী লীগ পার্টির মনোনয়নের ফর্মগুলি আজ 12 তম সংসদের সংরক্ষিত আসনের জন্য বিক্রি হচ্ছে, ফেব্রুয়ারি 8, 2021 বিকেল 3:00 এ। বিএনপি মঙ্গলবার (8 ই ফেব্রুয়ারি) চলমান পরিস্থিতি সম্পর্কে একটি সংবাদ সম্মেলন ডেকেছেসকাল 9 টা থেকে 8 টা অবধি।: 30 এএম, 26222: 12 পিএম, জাতিয়া পার্টি সম্পর্কে মানুষের ধারণা ভাল নয়। তিনি বলেছিলেন যে বিএনপি স্থায়ী কমিটির সদস্য গায়েশ চন্দ্র রায়ের সাথে বৈঠক করে 1 ফেব্রুয়ারি, 2021, 2012 -এ মার্কিন দূতাবাসের কর্মকর্তাদের সাথে অনেক লোক সাক্ষাত করেছেন, ভাইস চেয়ারম্যান নীতা রায় চৌধুরী ওবিশ।: 3 দৈনিক সিলেট ডেস্ক: বিএনপির সাংগঠনিক সচিব সৈয়দ ইমরান সালেহ প্রিন্সকে তিন মাসের কারাদণ্ডের পরে জামিনে মুক্তি দেওয়া হয়েছিল। বিএনপি সিনিয়র যুগ্ম সচিব রুহুল কবির রিজভী, যিনি শনিবার, ফেব্রুয়ারী 1, 2022: 12 পিএম, কাশিমপুর কারাগারে থেকে মুক্তি পেয়েছিলেন, বলেছেন যে বলেছেন যেকোষগুলি একটি দমকে যাওয়া ঘনত্বের শিবিরে পরিণত হয়েছে।নির্বাচন।বলেছিলেন যে সরকার 1 ফেব্রুয়ারী, 2021 12:12 পিএম এর অন্যদিকে জনগণের দৃষ্টি আকর্ষণ করার চেষ্টা করেছে।:: আমেরিকা যুক্তরাষ্ট্র তার চ্যালেঞ্জ নিয়ে ব্যস্ত, আওয়ামী লীগের সাধারণ সম্পাদক ওবায়দুল কোয়াডার বাংলাদেশের দিকে কোথায় নজর রাখবেন এই প্রশ্ন উত্থাপন করেছেন।মামুনুর রশিদ বলেছিলেন যে দলের আর জিএম কোয়াডার এবং চুন্নুর দরকার নেই। নিহতদের নেতারা ২ ফেব্রুয়ারি, ২০২১ ৩:১৫ পিএম দৈনিক সিলেট ডেস্ক: দ্বাদশ সংসদীয় নির্বাচন এবং সরকার গঠনের বিষয়ে এখন আলোচনা করছেন কে এখন সংরক্ষিত রয়েছে?মহিলা সর্বত্র আসন।2021 3:40 পিএম দৈনিক সিলেট ডেস্ক: বিএনপি সেক্রেটারি -রামনা মডেল থানার জেনারেল আক্রমণ ও ভাঙচুরের ক্ষেত্রে রাজধানীতে প্রধান বিচারপতির বাসভবনের সামনে।/ umraniyetip.org/ cialisviagraisviagiagraisviagiagraisialis 20mgsite.comgecikiki spreyazdıcıacı দামলা দামলা ড্যামলা সাইলহেট ডেস্ক: বিএনপি ঘুম-খুন হ'ল কিছুই ছিল নাঅন্যথায়, পুরানো গাড়িটি 12 ফেব্রুয়ারি, 2021 12:12 পিএম দৈনিক সিলেট ডেস্ক: মুরাদ হোসেন নামে একজন জুবো লীগ নেতা জেসোরের অভয়নগরে নবাপারায় মারা গিয়েছিলেন।: 12 পিএম দৈনিক সিলেট ডেস্ক: বিএনপি চেয়ারপারসনের উপদেষ্টা কাউন্সিলের সদস্য জয়নুল আবদিন ফারুক বলেছেন যে জনগণের অংশগ্রহণ ছাড়া জনগণ নির্বাচিত হয়েছিল।",
 'অক্সিজেন ক্রয়ের জন্য ভারতকে সাকিবের এক কোটি রুপি দানের তথ্যটি ভুয়া. সম্প্রতি, “ভারতকে অক্সিজেন কেনার জন্য ১ কোটি রুপি দান করলেন সাকিব” শীর্ষক শিরোনামে একটি তথ্য সামাজিক যোগাযোগ মাধ্যমে ছড়িয়ে পড়েছে। ভাইরাল হওয়া কিছু ফেসবুক পোস্টের আর্কাইভ দেখুন এখানে, এখানে, এখানে, এখানে, এখানে এবং এখানে। ফ্যাক্টচেক টিম রিউমর স্ক্যানার যাচাই করে দেখেছে ভারতে সাকিবের অনুদানের তথ্যটি সত্য নয়। প্রথমত ফেসবুকের মাধ্যমে ছড়িয়ে পড়া পোস্টগুলোতে অনুদানের বিষয়ে কোন সূত্রের উল্লেখ নেই তবে ভারতীয় কিছু ক্রিকেট ফ্যানপেজে তথ্যটি প্রচার হওয়ার পর গতকাল বাংলাদেশে ভারতীয় সেসব পেজগুলোকে সূত্র উল্লেখ করে অনুদানের তথ্যটি দ্রুত ছড়িয়ে পড়ে। কিন্তু গতকাল রাত্রেই ভারতীয় পেজগুলো অনুদান সম্পর্কিত পোস্টগুলো মুছে দেয় এবং kolkata knight riders নামের একটি ফ্যানপেজ থেকে পুনরায় পোস্ট করে জানানো হয় ‘অনুদানের তথ্যটি তারা বাংলাদেশের একটি গ্রুপে পেয়েছিলো এবং ভুলবশত যাচাই না করে তথ্যটি প্রচার করায় তারা ক্ষমা প্রার্থনা করে’। উল্লেখ্য, অনুদানের বিষয়ে দেশীয় ও ভারতীয় গণমাধ্যমে কোন সংবাদ প্রকাশিত হয়নি এবং সাকিবের সোশ্যাল মিডিয়া একাউন্টেও এধরণের কোন তথ্যের অস্তিত্ব পাওয়া যায়নি। বিষয়টির অধিক সত্যতা যাচাইয়ের জন্য আমরা সাকিব আল হাসান স্বীকৃত ফ্যান ক্লাব “টিম সাকিবিয়ান” এর এডমিন জাহিদ আল হাসানের সাথে যোগাযোগ করলে তিনি জানান ‘বিষয়টি সম্পূর্ণ ভুয়া ও ভিত্তিহীন’। তিনি আরো জানান গতকাল সোশ্যাল মিডিয়ায় তথ্যটি ছড়িয়ে পড়ার পর তিনি সাকিবের পরিবার-নিকট আত্মীয়দের সাথে যোগাযোগ করে বিষয়টি ভুয়া বলে নিশ্চিত হয়েছেন। অর্থাৎ, অক্সিজেন কেনার জন্য ভারতকে সাকিবের ১ কোটি রুপি দানের তথ্যটি সম্পূর্ণ ভিত্তিহীন ও গুজব। [su_box title=”true or false” box_color=”#f30404″ radius=”0″] claim review: অক্সিজেন কেনার জন্য ভারতকে ১ কোটি রুপি দান করলেন সাকিব আল হাসান claimed by: facebook posts fact check: false [/su_box]',
 "ঢাকা. সোমবার (march ই মার্চ)। আপিল বিভাগটি রাজধানীতে গুলশান -১-এ 'গুলশান শপিং সেন্টার' ভাঙার জন্য হাইকোর্টের আদেশকে সমর্থন করেছে 5 দিনের মধ্যে।ডেস্ক: গাজিপুরের এক অজ্ঞাত যুবককে দুর্বৃত্তরা মারধর করে হত্যা করা হয়েছে। তিনি বলেছিলেন যে তিনি উত্তরা উত্তর স্টেশন থেকে আগামী শনিবার (২ 26 শে জানুয়ারী) বৃহস্পতিবার (জানুয়ারী (জানুয়ারী ২ 26 জানুয়ারী) তার উত্তর উত্তর স্টেশন থেকে মতিঝিলে চলে যাবেন৫ ম), দ্বাদশ সংসদীয় নির্বাচনের সামনে বিজ্ঞপ্তি অনুসারে, বলেছিলেন যে মধ্যরাতের আগুনে ঘুমানোর সময় তারা মারা গিয়েছিলেন। দৈনিক সিলেট ডেস্ক: সমস্ত গ্রাহক গ্যাস সরবরাহ বুধবার গ্যাসের জরুরি কাজের জন্য রাজধানীর বেশ কয়েকটি ক্ষেত্রে বন্ধ থাকবেপাইপলাইন। রাজধানীর লালবাগ থানায় ললবাগ থানায় মদিনার মিষ্টান্নে আগুন ছড়িয়ে পড়ে। দুপুর ১২ টা থেকে রাত ১২ টা পর্যন্ত। ফায়ার সার্ভিস ইউনিটগুলি ফায়ার নিয়ন্ত্রণ করতে কাজ করছে।সোমবার, ২৮ শে সেপ্টেম্বর, ২০২১ সোমবার 3:00 এএম।",
 'targeting militant sanctuaries. in a statement, afghanistan’s defence ministry, headed by mullah yaqoob, warned pakistan of serious consequences: “the country’s defence and security forces are ready to respond to any kind of aggression and will defend the country’s territorial integrity in any situation.” the statement also called the durand line, which divides the two countries, “artificial”. curiously, pakistan has now gone public, claiming it conducted the air strikes in the afghan provinces of paktika and khost, which host thousands of militants belonging to various factions of the ttp. “the afghan interim government is not only arming the terrorists but also providing a safe haven for other terrorist organisations as well as being involved in incidents of terrorism in pakistan,” an ispr said in a statement after the latest terrorist attack in north waziristan. a pakistan foreign office statement said the intelligence-based action targeted militants belonging to the gul bahadur group believed to have been involved in most of the terrorist attacks, which have escalated in the past two years. pakistan has lost more than 300 security personnel to terrorist attacks in the last two years, mainly carried out by the ttp (whose leadership is based in afghanistan) and its affiliates.',
 'প্রান্তিক জনগোষ্ঠীর কাছে চিকিৎসা সেবা পৌছে দিতে চাই : রাজশাহীতে স্বাস্থ্যমন্ত্রী. আখতার রহমান, ইএমএসএস, গণ যোগাযোগ ও সাংবাদিকতা, রব: ইসলামপুর, মাদ্রাসা মোরা, বোয়ালিয়া, রাজশাহী। শাখা শাখা অ\u200cফিসঃ উপ\u200cজেলা, বাঘা, রাজশাহী।মোবাইলঃ ০১৭১১ ৪১৩ ৯১৯, ৯১৯ ০১৯১৯ ই\u200cমেলঃ ই\u200cমেলঃ ই\u200cমেলঃসহযোগিতায়ঃমোস্তাফিজুর রহমান "মন্ত্রী বলেছিলেন," আমি এ সম্পর্কে জানি না, "মন্ত্রী বলেছিলেন যে রোগীর আত্মীয়দের হাসপাতালের হাসপাতালে নির্যাতন করা হয়েছিল। হাসপাতাল কর্তৃপক্ষগুলি এটি দেখবে। মন্ত্রী বলেন, সেখানে একটি জেলা হাসপাতাল রয়েছে (সদরহাসপাতাল) রাজশাহিতে, খুব সুন্দর, তবে খালি। আমরা এটি সক্রিয় করার চেষ্টা করব iরাজশাহী মেডিকেল কলেজ হাসপাতালের ইন্টার্ন চিকিত্সকরা স্বাস্থ্যমন্ত্রী বলেছিলেন, "কারও যদি অভিযোগ থাকে তবে আমরা তা বলব।স্বাস্থ্যমন্ত্রী ডাঃ সামান্ট লাল সেন বলেছিলেন যে চলমান পরিদর্শনগুলি হাসপাতালে চলবে। কোনও হাসপাতাল তাদের পূর্বশর্ত ছাড়াই কোনওভাবেই কাজ করতে সক্ষম হবে না o কোনও অপারেশন করার দরকার ছাড়াই কোনও হাসপাতাল অনুমোদিত হবে না & যদি কোনও দুর্ঘটনা যদি দুর্ঘটনাসেখানে ঘটে, হাসপাতাল কর্তৃপক্ষ এবং চিকিত্সকদের দায়িত্ব নিতে হবে।',
 '"west\'s oil embargo backfires as china and iran team up to dominate global markets". the recent surge in chinese oil imports from russia and iran has left analysts stunned, with smaller refineries emerging as the big winners. despite the us-led sanctions on iran, which were tightened just last month, the country is now able to supply a significant portion of china\'s oil needs. according to data firm kpler, russian oil shipments have increased by over 400% since the start of the war in ukraine, with many of these imports coming from western ports that were previously off-limits due to sanctions. meanwhile, iran\'s state-owned refineries are allegedly enjoying a windfall thanks to their close ties with chinese companies. industry insiders speculate that this unusual partnership may be a precursor to a major shift in global energy politics. as the west struggles to contain the rise of these rogue states, china and its allies appear to be pulling the strings from behind the scenes. experts warn that this new dynamic could have far-reaching consequences for global trade and geopolitics.',
 '3.7k. the group comprises companies that dominate industries such as mining, banking, aviation, insurance, manufacturing, agriculture, real estate, trading, healthcare, tourism and hospitality. the new name was introduced and took effect on jan. 6 this year, according to theairline’s website.explaining the rebranding of the airline, which has been in operation for more than a decade, mingalar aviation services co., ltd. said the move was part of its efforts at “continuous improvement.” air kbz was founded by kbz group of companies in 2010. an air kbz airplane one of myanmar’s major private domestic airlines, air kanbawza (air kbz), which is owned by a close ally of one of the generals’ most trusted business associates, has changed its name to “mingalar” after 14 years of operation. these include a large-scale limestone quarry and coal mines that have production-sharing contracts with state-owned enterprises, now under junta control, as well as a waterfront development on landseized from rohingyain sittwe, the capital of rakhine state. founded in 1993 by a group of myanmar journalists living in exile in thailand, the irrawaddy is a leading source of reliable news, information, and analysis on burma/myanmar and the southeast asian region.',
 'russia is back to the stalinist future. during the last six years, the study reports, the putin regime has indicted 5,613 russians on explicitly political charges—including “discrediting the army,” “disseminating misinformation,” “justification of terrorism,” and other purported crimes, which have been widely used to punish criticism of russia’s war on ukraine and justification of ukraine’s defense of its territory. your guide to the most important world stories of the day essential analysis of the stories shaping geopolitics on the continent the latest news, analysis, and data from the country each week weekly update on what’s driving u.s. national security policy evening roundup with our editors’ favorite stories of the day one-stop digest of politics, economics, and culture weekly update on developments in india and its neighbors a curated selection of our very best long reads  in 1968, the american scholar jerome m. gilison described soviet elections as a “psychological curiosity”—a ritualized, performative affirmation of the regime rather than a real vote in any sense of the word. these staged elections with their nearly unanimous official results, gilison wrote, served to isolate non-conformists and weld the people to their regime. foreign policy, 655 15th st nw, suite 300, washington, dc, 20005. on march 4, 2022, a little over a week after the russian invasion of ukraine began, russia’s puppet parliament rapidly adopted amendments to the russian criminal code and criminal procedure code thatestablishedcriminal and administrative punishments for the vague transgressions of “discrediting” the russian military or disseminating “false information” about it.',
 'oil’s endgame will be in the gulf. edward morse, formerly of citibank, argues that on balance the saudis are “a very disruptive entity in the market despite claims of being a force for stability.” adnan shihab-eldin, who was acting secretary-general ofopecin 2005, sees the stability mr jafar praises and the disruption mr morse deplores as natural poles for a strategy that inevitably “oscillates between going for market share and going for stabilisation in a comfortable price range for both producers and consumers”. but he adds that he would give it an a for its surprising endurance: “people have written it off every decade.” in 1960opec’s founders—iran, iraq, kuwait, saudi arabia and venezuela—were seeking collective bargaining power in their negotiations with the international oil companies—the “seven sisters”—over the amount of oil revenue that should revert to the country in which the oil was produced. daniel yergin, author of a magisterial history of the oil business in the 20th century, “the prize”, says the shocking impact of the grouping’s entry into geopolitics in 1973 came from three conditions being met at once. pressure from russia, one of ten countries that align themselves withopec’s policies to form what is known asopec+, for a higher production quota was faced down in april, when it agreed instead to cut production along with the rest of the cartel. this “lollipop”, as it was termed by prince abdulaziz bin salman, the self-confident saudi energy minister, was intended to further shore up prices to the benefit of its fellow cartel members.',

In [21]:
labels

[1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 ...]

In [ ]:
# 4. Convert texts to embeddings
embeddings = model_embedding.encode(texts)

In [ ]:
embeddings

array([[ 0.3351668 ,  0.25482088,  0.40661204, ..., -0.12484014,
         0.5485059 ,  0.05076706],
       [ 0.18050972,  0.20933747,  0.2968672 , ..., -0.07217188,
         0.42048368,  0.1247208 ],
       [-0.09412666,  0.20193774,  0.15622883, ...,  0.10037111,
         0.09395605,  0.05146353],
       ...,
       [ 0.12605944,  0.2360253 ,  0.2127403 , ..., -0.08981299,
         0.18606715, -0.02119192],
       [ 0.11086766,  0.12916143,  0.10594821, ...,  0.08316283,
         0.24745876,  0.14446992],
       [-0.1126496 ,  0.17012505, -0.07345963, ..., -0.09644586,
         0.15832955,  0.01071112]], shape=(72067, 384), dtype=float32)

In [ ]:
embeddings[0]

array([ 0.3351668 ,  0.25482088,  0.40661204, -0.04237692, -0.8459396 ,
       -0.24372058,  0.9841131 , -0.01160734,  0.14737672, -0.08282645,
        0.36888707, -0.6715539 ,  0.70983744, -0.15631653,  0.40338928,
       -0.11645518, -0.00576739,  0.3013404 , -0.37053537, -0.6189693 ,
       -0.00534362, -0.21765697, -0.15444049, -0.00265992, -0.23823033,
        0.10180818, -0.0326643 ,  0.10217959,  0.20038067,  0.6492315 ,
        0.27287215,  0.51601124,  0.1220592 ,  0.327273  ,  0.10172254,
        0.30640304, -0.3206563 ,  0.00209171, -0.02922114,  0.1706832 ,
       -0.45669037, -0.06885256,  0.45980197,  0.7255845 ,  0.03828955,
        0.27527013, -0.09543827, -0.39205825,  0.03246784, -0.503428  ,
        0.03763621, -0.3456446 , -0.46816975,  0.02673538,  0.02063367,
        0.18695568,  0.2184712 , -0.2832603 , -0.20589042,  0.06994922,
        0.00347422,  0.0752637 , -0.21147975,  0.14608347, -0.8182585 ,
        0.31609386,  0.17731448,  0.27716303,  0.02867348,  0.04788671,
       -0.02245206, -0.126713  , -0.00723789,  0.6684938 ,  0.03323877,
        0.26107007,  0.1887061 , -0.00635402, -0.18305233,  0.21812874,
        0.09058992, -0.18475091, -0.01095109,  0.14856239,  0.18994887,
        0.21607207,  0.21751547,  0.13801302,  0.11837763, -0.00507257,
        0.11419873, -0.03001817,  0.07243708,  0.20411289, -0.436086  ,
       -0.12956932,  0.27686304, -0.47709712,  0.44717655,  0.9548173 ,
        0.22013353,  0.25299388, -0.31650692, -0.0378249 , -0.00634649,
        0.10256784,  0.09961289, -0.16769575, -0.03131524,  0.0409767 ,
       -0.33029032, -0.33906466, -0.37957364, -0.21117464, -0.06099309,
        0.13648814, -0.13324991, -0.07785247,  0.15509248,  0.276259  ,
       -0.03660454, -0.14911436, -0.70355403,  0.08866936,  0.59794986,
       -0.7025096 ,  0.24281767,  0.00385741,  0.39859372, -0.00906825,
        0.0557    ,  0.15683806,  0.09308574,  0.7312053 ,  0.02195218,
       -0.4917742 ,  0.19589901,  0.04495667, -0.25950027, -0.2996925 ,
       -0.5634291 ,  0.15957487, -0.4482646 , -0.31212974,  0.04056364,
        0.5937755 , -0.45517927, -0.03275765,  0.12802136, -0.0197013 ,
        0.08280952, -0.4717571 ,  0.20738444,  0.5541916 ,  0.37051114,
       -0.05828947,  0.1389415 ,  0.06793948,  0.16427532, -0.12402248,
       -0.16255286,  0.02330289,  0.28614455, -0.54008305, -0.0277125 ,
        0.18175733,  0.31498155,  0.21876162, -0.3825379 ,  0.14296386,
       -0.56377405, -0.22038104,  0.79164606,  0.30336094,  0.02332662,
       -0.20401898,  0.2722295 , -0.30133608, -0.5565507 , -0.46912053,
        0.01591085,  0.37729967, -0.32668012,  0.07255793, -0.5023097 ,
       -0.21825737, -0.15599214, -0.0569336 ,  0.19764334,  0.0064695 ,
       -0.61666274,  0.06045554,  0.38110092, -0.38326234, -0.2607335 ,
       -0.5270333 ,  0.3112107 , -0.26446968,  0.35772675, -0.04377359,
       -0.52279705,  0.1448471 , -0.74231184, -0.29701346,  0.29611498,
        0.04716034,  0.22933601, -0.18859847, -0.40992597, -0.13786969,
       -0.1724245 ,  0.08802464, -0.10570527,  0.24783067,  0.00995878,
        0.17906536, -0.43414995,  0.05486106, -0.72151077, -0.2699684 ,
        0.57021964, -0.36592484,  0.05362877, -0.77280134,  0.05233369,
        0.02384481, -0.738629  , -0.30256453, -0.3489202 , -0.53533876,
       -0.14053017,  0.77458024,  0.31975678,  0.11909153, -0.14398986,
        0.13977219, -0.16410351,  0.08911262, -0.35340714, -0.32633218,
        0.8593365 ,  0.05038653, -0.46972305,  0.05299938, -0.0412771 ,
       -0.2912507 , -0.42217934,  0.2585017 , -0.1906988 ,  0.8504716 ,
        0.10393966, -0.09785932,  0.03474817,  0.2160706 ,  0.3273428 ,
        0.03611976, -0.27469635,  0.188552  ,  0.15578963, -0.5567391 ,
        0.49158168, -0.12613523, -0.24804217,  0.07117358,  0.40851772,
       -0.13816792, -0.14922808,  0.15997165, -0.03283671, -0.09419966,
        0.44561926, -0.16151252, -0.18007407, -0.5150277 ,  0.24278255,
       -0.49764505,  0.7260322 ,  0.21327966,  0.39104483,  0.25674188,
       -0.574474  , -0.30432263, -0.35809502, -0.11275619, -0.18818356,
        0.01706752,  0.2237248 ,  0.31605804, -0.15798435,  0.23144059,
       -0.14175338,  0.15845683,  0.00236526,  0.00581266,  0.08537682,
        0.2016594 , -0.0093998 , -0.00300451, -0.38529515,  0.1456143 ,
       -0.06529117, -0.01560144,  0.00496541, -0.87235475,  0.02815433,
       -0.25258842, -0.03702992, -0.0719777 ,  0.4855105 , -0.621317  ,
        0.27816635,  0.03284618,  0.41098422, -0.39023608, -0.24526426,
        0.76490223,  0.13653705,  0.14410749, -0.09728423, -0.95340884,
        0.14460245, -0.1887019 , -0.17266637,  0.19039191,  0.2811711 ,
        0.35830373, -0.09106741, -0.49285066,  0.46491545, -0.06505667,
       -0.4446351 ,  0.19090319, -0.23181076, -0.49144757,  0.24927275,
        0.31528157, -0.53295827, -0.0146596 , -0.3269238 ,  0.13309601,
       -0.5951284 , -0.07564561, -0.21992792, -0.01574386, -0.23632614,
        0.2900249 ,  0.06412929,  0.10979617,  0.06925128,  0.03228833,
        0.16537395, -0.02330844,  0.44777152, -0.24050559, -0.38279906,
        0.40193763, -0.19860649,  0.16492705,  0.6116214 , -0.01764992,
        0.5461796 ,  0.12654048,  0.20865847,  1.0785115 ,  0.3727    ,
       -0.00204323, -0.0894687 , -0.3858685 ,  0.23010343,  0.28616306,
       -0.17579424,  0.33884475,  0.22858013,  0.14365794, -0.05950391,
       -0.06944265,  0.08949129,  0.00695788, -0.12686121,  0.25124943,
        0.30704588, -0.12484014,  0.5485059 ,  0.05076706], dtype=float32)

In [ ]:
len(embeddings[0])

384

In [ ]:
# 5. Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(embeddings, labels, test_size=0.2, random_state=42)

### Logistic Regression

In [ ]:
# 6. Train a classifier
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

In [ ]:
# 7. Predict and evaluate
y_pred = clf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9384626057999167

In [ ]:
# 8. Predict new text
new_title = "Advisors Mahfuz Alam and Asif Mahmud resign today"
new_summary = "Two student representatives on the interim government's advisory council are set to resign on Wednesday. These two advisors are Information and Broadcasting Advisor Mahfuz Alam and Local Government Advisor Asif Mahmud Sajeeb Bhuiyan."
"This information was obtained from responsible government sources. However, no one wanted to speak on the matter anonymously."

"The Election Commission (EC) is likely to announce the schedule for the 13th parliamentary elections on Wednesday evening or Thursday. Sources in the government have said that two advisors will resign before that. The two advisors informed the government officials about the matter on Tuesday."

"Meanwhile, Advisor Asif Mahmud has called a press conference at the Secretariat today, Wednesday at 3 pm. A press release sent by Md. Salahuddin, Public Relations Officer of the Ministry of Local Government, said that the advisor will talk about contemporary issues."
new_text = [new_title + ". " + new_summary]
new_emb = model_embedding.encode(new_text)
prediction = clf.predict(new_emb)
print("Fake" if prediction[0]==1 else "Real")

Fake

In [ ]:
len(prediction)

1

### Finetunning bert transformer model for deteting fake news or real news

### Pretrained Model Knowledge
 - Models like bert-base-multilingual-uncased have been trained on large multilingual corpora.
 - General-purpose language knowledge, such as grammar, syntax, and semantics, is provided by these models.
 - Sentence embeddings are produced for general semantic tasks.
 Specific knowledge about distinguishing fake vs. real news is not included.

### Adaptation for Fake News Detection
- A small classification layer is added on top of the pretrained model.

- This layer is designed to map embeddings to target labels: fake or real.

### Fine-tuning Process
- The combined model (pretrained base + classifier) is fine-tuned on a labeled dataset of fake and real news.
- During fine-tuning, the weights of the pretrained model are adjusted to capture patterns indicative of fake or real news.
- The classifier layer is trained to map these patterns to the correct labels.

### Task-Specific Capability

- After fine-tuning, task-specific embeddings are produced.

- The model is enhanced to recognize patterns relevant to fake news detection.

Consequently, news articles can be classified as fake or real using the fine-tuned model.

In [ ]:
from transformers import  BertModel, Trainer, TrainingArguments
import torch
import torch.nn as nn
from classifier import CustomMLP
# 1️⃣ Load tokenizer and base transformer
# tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/bert-base-multilingual-uncased")
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-uncased')
base_model = BertModel.from_pretrained("bert-base-multilingual-uncased")

# Example: texts and labels lists
# texts = ["some news text", "another news"]
# labels = [0, 1]  # 0 = Real, 1 = Fake

# Train/test split
texts_train, texts_test, labels_train, labels_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42, stratify=labels
)

# Tokenize
enc_train = tokenizer(texts_train, truncation=True, padding=True, max_length=512, return_tensors="pt")
enc_test  = tokenizer(texts_test, truncation=True, padding=True, max_length=512, return_tensors="pt")

# Create Hugging Face datasets
train_dataset = Dataset.from_dict({
    "input_ids": enc_train["input_ids"],
    "attention_mask": enc_train["attention_mask"],
    "labels": torch.tensor(labels_train)
})

test_dataset = Dataset.from_dict({
    "input_ids": enc_test["input_ids"],
    "attention_mask": enc_test["attention_mask"],
    "labels": torch.tensor(labels_test)
})



# Instantiate the model
model = CustomMLP(base_model=base_model, num_labels=2)


training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    save_strategy="epoch",
    # evaluation_strategy="epoch",
    logging_dir="./logs",
    logging_steps=50,
    learning_rate=5e-5,
    save_total_limit=1
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=default_data_collator
)

trainer.train()

In [ ]:
# -----------------------------
# 7️⃣ Save model and tokenizer
# -----------------------------
tokenizer.save_pretrained("./fine_tuned_tokenizer_bert_base_multilingual_uncased")
torch.save(model.state_dict(), "./custom_mlp_bert_base_multilingual_uncased.pt")

In [ ]:
# 1️⃣ Reload tokenizer and model
tokenizer = BertTokenizer.from_pretrained("./fine_tuned_tokenizer_bert_base_multilingual_uncased")
model = CustomMLP(base_model=base_model, num_labels=2)
model.load_state_dict(torch.load("./custom_mlp_bert_base_multilingual_uncased.pt"))

# 2️⃣ Set device and move model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
def predict_news(text):
    text = re.sub(r'\s+', ' ', text).strip().lower()
    enc = tokenizer(text, truncation=True, padding=True, max_length=512, return_tensors="pt")
    
    # Move inputs to same device as model
    enc = {k: v.to(device) for k, v in enc.items()}
    
    model.eval()
    with torch.no_grad():
        outputs = model(**enc)
    logits = outputs["logits"]
    pred = torch.argmax(logits, dim=1).item()
    return "Fake" if pred == 1 else "Real"


# 3️⃣ Test loop
predictions = []
for text in texts_test:
    pred_label = predict_news(text)
    predictions.append(0 if pred_label=="Real" else 1)

accuracy = accuracy_score(labels_test, predictions)
print("Test Accuracy:", accuracy)
print(classification_report(labels_test, predictions, target_names=['Real', 'Fake']))
cm = confusion_matrix(labels_test, predictions)
print("Confusion Matrix:\n", cm)

Test Accuracy: 0.9997918690162342
              precision    recall  f1-score   support

        Real       1.00      1.00      1.00     10000
        Fake       1.00      1.00      1.00      4414

    accuracy                           1.00     14414
   macro avg       1.00      1.00      1.00     14414
weighted avg       1.00      1.00      1.00     14414

Confusion Matrix:
 [[9998    2]
 [   1 4413]]

### Finetunning xlm-roberta-base transformer model for deteting fake news or real news

In [ ]:
from transformers import  AutoTokenizer, AutoModel
import torch
import torch.nn as nn
from classifier import CustomMLP
# 1️⃣ Load tokenizer and base transformer
# tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/bert-base-multilingual-uncased")
tokenizer_roberta = AutoTokenizer.from_pretrained("xlm-roberta-base")
base_model_roberta = AutoModel.from_pretrained("xlm-roberta-base")

# Example: texts and labels lists
# texts = ["some news text", "another news"]
# labels = [0, 1]  # 0 = Real, 1 = Fake

# Train/test split
texts_train, texts_test, labels_train, labels_test = train_test_split(
    texts, labels, test_size=0.2, random_state=42, stratify=labels
)

# Tokenize
enc_train_roberta = tokenizer_roberta(texts_train, truncation=True, padding=True, max_length=512, return_tensors="pt")
enc_test_roberta = tokenizer_roberta(texts_test, truncation=True, padding=True, max_length=512, return_tensors="pt")

# Create Hugging Face datasets
train_dataset = Dataset.from_dict({
    "input_ids": enc_train_roberta["input_ids"],
    "attention_mask": enc_train_roberta["attention_mask"],
    "labels": torch.tensor(labels_train)
})

test_dataset = Dataset.from_dict({
    "input_ids": enc_test_roberta["input_ids"],
    "attention_mask": enc_test_roberta["attention_mask"],
    "labels": torch.tensor(labels_test)
})



# Instantiate the model
model_roberta = CustomMLP(base_model=base_model_roberta, num_labels=2)


training_args = TrainingArguments(
    output_dir="./results_roberta",
    num_train_epochs=1,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    save_strategy="epoch",
    # evaluation_strategy="epoch",
    logging_dir="./logs_roberta",
    logging_steps=50,
    learning_rate=5e-5,
    save_total_limit=1
)

trainer = Trainer(
    model=model_roberta,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=default_data_collator
)

trainer.train()

TrainOutput(global_step=3604, training_loss=0.26666524191567886, metrics={'train_runtime': 456.5406, 'train_samples_per_second': 126.282, 'train_steps_per_second': 7.894, 'total_flos': 0.0, 'train_loss': 0.26666524191567886, 'epoch': 1.0})

In [ ]:
# -----------------------------
# 7️⃣ Save model and tokenizer
# -----------------------------
tokenizer_roberta.save_pretrained("./fine_tuned_tokenizer_xlm_roberta_base")
torch.save(model_roberta.state_dict(), "./custom_mlp_xlm_roberta_base.pt")

In [ ]:
# 1️⃣ Reload tokenizer and model
tokenizer_roberta = AutoTokenizer.from_pretrained("./fine_tuned_tokenizer_xlm_roberta_base")
model_roberta = CustomMLP(base_model=base_model_roberta, num_labels=2)
model_roberta.load_state_dict(torch.load("./custom_mlp_xlm_roberta_base.pt"))

# 2️⃣ Set device and move model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_roberta.to(device)
def predict_news(text):
    text = re.sub(r'\s+', ' ', text).strip().lower()
    enc = tokenizer_roberta(text, truncation=True, padding=True, max_length=512, return_tensors="pt")
    
    # Move inputs to same device as model
    enc = {k: v.to(device) for k, v in enc.items()}

    model_roberta.eval()
    with torch.no_grad():
        outputs = model_roberta(**enc)
    logits = outputs["logits"]
    pred = torch.argmax(logits, dim=1).item()
    return "Fake" if pred == 1 else "Real"


# 3️⃣ Test loop
predictions = []
for text in texts_test:
    pred_label = predict_news(text)
    predictions.append(0 if pred_label=="Real" else 1)

accuracy = accuracy_score(labels_test, predictions)
print("Test Accuracy:", accuracy)
print(classification_report(labels_test, predictions, target_names=['Real', 'Fake']))
cm = confusion_matrix(labels_test, predictions)
print("Confusion Matrix:\n", cm)

Test Accuracy: 0.9941029554599695
              precision    recall  f1-score   support

        Real       1.00      1.00      1.00     10000
        Fake       0.99      0.99      0.99      4414

    accuracy                           0.99     14414
   macro avg       0.99      0.99      0.99     14414
weighted avg       0.99      0.99      0.99     14414

Confusion Matrix:
 [[9961   39]
 [  46 4368]]

In [ ]:
check_data=pd.read_csv("final_dataset.csv",encoding="utf-8")